import React from 'react';
import { motion } from 'framer-motion';

const GALLERY_ITEMS = [
    {
        id: 1,
        image: 'https://images.unsplash.com/photo-1595959183082-7bce70848dd8?w=500&q=80',
        title: 'Modern Chic',
        category: 'Fashion'
    },
    {
        id: 2,
        image: 'https://images.unsplash.com/photo-1620331311520-246422fd82f9?w=500&q=80',
        title: 'Textured Crop',
        category: 'Hairstyle'
    },
    {
        id: 3,
        image: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=500&q=80',
        title: 'Summer Breeze',
        category: 'Fashion'
    },
    {
        id: 4,
        image: 'https://images.unsplash.com/photo-1580618672591-eb180b1a973f?w=500&q=80',
        title: 'Long Waves',
        category: 'Hairstyle'
    },
    {
        id: 5,
        image: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?w=500&q=80',
        title: 'Street Style',
        category: 'Fashion'
    },
    {
        id: 6,
        image: 'https://images.unsplash.com/photo-1585747860715-2ba37e788b70?w=500&q=80',
        title: 'Buzz Cut',
        category: 'Hairstyle'
    }
];

export default function Gallery() {
    return (
        <div className="min-h-screen pt-24 px-6 pb-12">
            <div className="max-w-7xl mx-auto">
                <motion.div
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    className="text-center mb-16"
                >
                    <h1 className="text-4xl md:text-5xl font-bold mb-6">Style Gallery</h1>
                    <p className="text-xl text-white/60">
                        Explore trending looks generated by our AI.
                    </p>
                </motion.div>

                <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
                    {GALLERY_ITEMS.map((item, index) => (
                        <motion.div
                            key={item.id}
                            initial={{ opacity: 0, scale: 0.9 }}
                            animate={{ opacity: 1, scale: 1 }}
                            transition={{ delay: index * 0.1 }}
                            className="group relative aspect-[3/4] rounded-2xl overflow-hidden cursor-pointer"
                        >
                            <img
                                src={item.image}
                                alt={item.title}
                                className="w-full h-full object-cover transition-transform duration-500 group-hover:scale-110"
                            />
                            <div className="absolute inset-0 bg-gradient-to-t from-black/80 via-transparent to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-300" />
                            <div className="absolute bottom-0 left-0 right-0 p-6 translate-y-full group-hover:translate-y-0 transition-transform duration-300">
                                <span className="text-sm font-medium text-blue-400 mb-1 block">
                                    {item.category}
                                </span>
                                <h3 className="text-xl font-bold">{item.title}</h3>
                            </div>
                        </motion.div>
                    ))}
                </div>
            </div>
        </div>
    );
}
